Repository magento/architecture, pull requests merged in 2019-08, with the labels that each got.

#171 Background Processes - Draft 1
  design-documents/background-processes/background-processes-proposal.md
Labels: Partner: JH, partners-contribution

#190 MFTF: Friendly labels to elements, actions and action groups
  design-documents/testing/functional/bdd-like-mftf-output.md
Labels: Partner: Strix, partners-contribution

#207 DTO proposal
  design-documents/dto/proposal.md
Labels: Partner: MageSpecialist, partners-contribution, proposal
