Repository magento/architecture, pull requests merged in 2019-10, with the labels that each got.

#274 Cart operations GraphQl Schema actualization and in store pickup support
  design-documents/graph-ql/coverage/CartAddressOperations.graphqls
Labels: Partner: ISM eCompany, partners-contribution

#200 Added the proposal for Abstract Method removal
  design-documents/abstract-method-removal.md
Labels: proposal, tech vision

#318 DB Information Schema - COLUMNS
  design-documents/database/declarative-schema-database-compatibility.md
Labels: Partner: TechDivision, partners-contribution

#301 MC-19826: Adds investigation on removal of dependency on Auto_Increment
  design-documents/Investigation-on-removal-of-dependency-on-Auto_Increment-Id-in-application.md
Labels: Partner: TechDivision, partners-contribution

#315 [ARC-596] Introduce Server-Side Rendering doc
  design-documents/frontend/server-side-rendering.md
Labels: open discussion
