Repository magento/architecture, pull requests merged in 2020-07, with the labels that each got.

#381 B2B NegotiableQuote GraphQL Schema
  design-documents/graph-ql/coverage/negotiableQuotes.graphqls
Labels: Partner: Zilker Technology, partners-contribution

#376 Refactor B2B Company Structure query to remove recursive type and add more edges
  design-documents/graph-ql/coverage/company.md
Labels: GraphQL

#337 magento/graphql-ce#196: Swatches: expose Hex color code and swatch images
  design-documents/graph-ql/coverage/Swatches.graphqls
Labels: GraphQL

#410 Company schema changes to describe behavior and fix some return types
  design-documents/graph-ql/coverage/company.md
Labels: GraphQL

#399 Iterating on Negotiable Quote GraphQL schema design
  design-documents/graph-ql/coverage/negotiableQuotes.graphqls
Labels: GraphQL

#391 req list items pagiantion
  design-documents/graph-ql/coverage/requisitionList.graphqls
Labels: GraphQL, Partner: Zilker Technology, partners-contribution

#407 Remove global uniqueness requirement from graphql single add to cart …
  design-documents/graph-ql/coverage/add-items-to-cart-single-mutation.md
Labels: GraphQL
