Repository magento/architecture, pull requests merged in 2020-08, with the labels that each got.

#31 OMCONNECT-91: Add OPTIONS to Allowed Methods in Web Api
  design-documents/Add-Options-to-Allowed-Methods-in-Web-Api.md
Labels: needs update

#413 Proposal to solve dependency in GQL schema between QuoteGQL and WishlistGQL
  design-documents/graph-ql/coverage/AddProductsToCart.graphqls
Labels: GraphQL

#188 Support JWT out-of-box
  design-documents/img/jwt-api-authorization.png
  design-documents/img/jwt-class-diagram.png
  design-documents/img/jwt-data-exchange.png
  design-documents/img/jwt-data-verification.png
  design-documents/img/jwt-user-authorization.png
  design-documents/jwt-support.md
Labels: proof of concept, proposal

#416 GiftWrapping changes on proposed schema
  design-documents/graph-ql/coverage/gift-wrapping.md
Labels: GraphQL

#397 ECP-766: Returns Schema Design
  design-documents/graph-ql/coverage/returns.graphqls
  design-documents/graph-ql/coverage/returns.md
Labels: GraphQL

#415 MC-36347: ID Improvement Plan
  design-documents/graph-ql/id-improvement-plan.md
Labels: GraphQL

#388 Added replace or merge option for addRequisitionListItemToCart mutation
  design-documents/graph-ql/coverage/requisitionList.graphqls
Labels: GraphQL, Partner: Zilker Technology, partners-contribution

#427 magento2/issues/29479 Returns : graphql implementation
  design-documents/graph-ql/coverage/returns.graphqls
  design-documents/graph-ql/coverage/returns.md
Labels: GraphQL

#428 Document existing GraphQL naming conventions
  design-documents/graph-ql/naming-conventions.md
Labels: GraphQL
